### ISSUE TITLE
command can´t be executed

### ISSUE THREAD

**Issue by mercadanteus** [NullPointer-Nico/WarpSystem#1]
Hello, I'd appreciate your help with this problem, first day the plugin worked, today I can't use it, I have this message:  "unknown error trying to execute this command", here is the console log:  

https://hastebin.com/qofipanefu

**Comment by NullPointer-Nico-zz** [comment]
Hello, I will fixx the error as soon as it goes. Thank you for the information.

**Comment by NullPointer-Nico-zz** [comment]
Its fixxed download the newest version on cloudburst.
